Revises the Indexer to improve failure handling and logging (#502).
emory-libraries/blacklight-catalog pull request #521
Opened 2021-05-07 17:30 UTC by bwatson78

- .gitignore: ignores any new log file posted into root folder.
- app/loggers/oai_mmsid_logger.rb and app/loggers/blackcat_logger.rb: removes these loggers in favor of Rails built-in class.
- app/services/oai_processing_service.rb: 
     - completely refactors the long processing method into smaller method calls.
     - removes the skip to another processing method that was there whenever we had two indexers going.
     - uses the Rails Logger to announce any errors or pertinent information for debugging.
     - escapes the method (and therefore rake task) if errors occur during API calls.
     - now uses RSolr to post ids needed for deletion.
     - switches to Faraday to communicate with OAI service.
- lib/marc_indexer.rb: makes Traject's default SolrWriter stop once an error is detected. Also increases the http timeout talking with Solr to 4 minutes.
- lib/tasks/marc_index_ingester.rake: institutes a Rails Logger and swaps it for the STDOUT.
- spec/*: swaps to the Rails Logger and removes expectation for the method skip.

2021-05-07 17:30 UTC, bwatson78 commented
No screenshots necessary.

2021-05-10 14:38 UTC, rotated8 requested changes
There are a couple places where it feels like we could improve performance by reducing the number of method calls we make. Can you take a look and advise?

2021-05-10 14:51 UTC, bwatson78 commented on app/services/oai_processing_service.rb
> +  end
Will do.

2021-05-10 14:52 UTC, bwatson78 commented on app/services/oai_processing_service.rb
> +  end
I agree, they should be constants.

2021-05-10 15:21 UTC, bwatson78 commented on app/services/oai_processing_service.rb
> +  end
Change made.

2021-05-10 15:22 UTC, bwatson78 commented
@rotated8 All changes have been addressed.

2021-05-10 16:17 UTC, merged